
--1
SELECT 
kh.MAKHACHHANG, 
ncc.TENCONGTY, 
kh.TENGIAODICH
FROM KHACHHANG kh
INNER JOIN NHACUNGCAP ncc ON kh.TENGIAODICH = ncc.TENGIAODICH;

--2
SELECT
ddh.SOHOADON,
ddh.NGAYDATHANG,
ddh.NGAYGIAOHANG
FROM DONDATHANG ddh
WHERE TO_CHAR(ddh.NGAYDATHANG, 'DD-MM-YYYY') = TO_CHAR(ddh.NGAYGIAOHANG, 'DD-MM-YYYY');

--3
SELECT 
mh.MAHANG
FROM MATHANG mh
WHERE mh.MAHANG NOT IN (SELECT ctdh.MAHANG FROM CHITIETDATHANG ctdh);

--4
SELECT 
nv.MANHANVIEN,
nv.HO,
nv.TEN
FROM NHANVIEN nv
WHERE nv.MANHANVIEN NOT IN (SELECT DISTINCT ddh.MANHANVIEN FROM DONDATHANG ddh);

--5
SELECT
ctdh.MAHANG
FROM CHITIETDATHANG ctdh
WHERE ctdh.MAHANG 
IN (SELECT
ctdh.MAHANG
FROM DONDATHANG ddh
INNER JOIN CHITIETDATHANG ctdh ON ddh.SOHOADON = ctdh.SOHOADON
AND TO_CHAR(ddh.NGAYDATHANG, 'YYYY')='2017')
GROUP BY ctdh.MAHANG
HAVING COUNT(ctdh.MAHANG)=1;

--6
SELECT 
ddh.MAKHACHHANG,
SUM(ctdh.GIABAN*ctdh.SOLUONG + ctdh.GIABAN*ctdh.SOLUONG*(ctdh.MUCGIAMGIA/100)) AS TONGTIEN
FROM DONDATHANG ddh
INNER JOIN CHITIETDATHANG ctdh ON ddh.SOHOADON = ctdh.SOHOADON
GROUP BY ddh.MAKHACHHANG;

--7
SELECT
nv.MANHANVIEN,
COUNT(ddh.MANHANVIEN) AS LANLAPDON
FROM NHANVIEN nv
LEFT OUTER JOIN DONDATHANG ddh ON nv.MANHANVIEN = ddh.MANHANVIEN 
GROUP BY nv.MANHANVIEN;

--8
SELECT
TO_CHAR(ddh.NGAYDATHANG, 'MM') AS THANG,
SUM((ctdh.GIABAN*ctdh.SOLUONG + ctdh.GIABAN*ctdh.SOLUONG*(ctdh.MUCGIAMGIA/100))) AS TONGTIEN
FROM DONDATHANG ddh
LEFT OUTER JOIN CHITIETDATHANG ctdh ON ddh.SOHOADON = ctdh.SOHOADON
AND TO_CHAR(ddh.NGAYDATHANG, 'YYYY')='2017' 
GROUP BY TO_CHAR(ddh.NGAYDATHANG, 'MM');

--9
SELECT
mh.MAHANG,
SUM(mh.SOLUONG) AS TRONGKHO,
SUM(ctdh.SOLUONG) AS DABAN
FROM MATHANG mh
LEFT OUTER JOIN CHITIETDATHANG ctdh ON mh.MAHANG = ctdh.MAHANG
GROUP BY mh.MAHANG;

--10
SELECT
aa.MANHANVIEN,
aa.HO,
aa.TEN,
aa.MAXHANG
FROM (SELECT
ddh.MANHANVIEN,
nv.HO,
nv.TEN,
SUM(ctdh.SOLUONG) AS MAXHANG,
SUM((ctdh.GIABAN*ctdh.SOLUONG + ctdh.GIABAN*ctdh.SOLUONG*(ctdh.MUCGIAMGIA/100))) AS TONGTIEN
FROM DONDATHANG ddh
INNER JOIN CHITIETDATHANG ctdh ON ctdh.SOHOADON = ddh.SOHOADON
INNER JOIN NHANVIEN nv ON nv.MANHANVIEN = ddh.MANHANVIEN
GROUP BY ddh.MANHANVIEN, nv.HO, nv.TEN) aa,

(SELECT
MAX(MAXHANG) AS MAXHANG
FROM (SELECT
ddh.MANHANVIEN,
nv.HO,
nv.TEN,
SUM(ctdh.SOLUONG) AS MAXHANG,
SUM((ctdh.GIABAN*ctdh.SOLUONG + ctdh.GIABAN*ctdh.SOLUONG*(ctdh.MUCGIAMGIA/100))) AS TONGTIEN
FROM DONDATHANG ddh
INNER JOIN CHITIETDATHANG ctdh ON ctdh.SOHOADON = ddh.SOHOADON
INNER JOIN NHANVIEN nv ON nv.MANHANVIEN = ddh.MANHANVIEN
GROUP BY ddh.MANHANVIEN, nv.HO, nv.TEN)) cc
WHERE aa.MAXHANG = cc.MAXHANG;

--11
SELECT
ctdh.SOHOADON,
SUM((ctdh.GIABAN*ctdh.SOLUONG + ctdh.GIABAN*ctdh.SOLUONG*(ctdh.MUCGIAMGIA/100))) AS TONGTIEN
FROM CHITIETDATHANG ctdh
GROUP BY ctdh.SOHOADON;

SELECT
ctdh.SOHOADON,
mh.TENHANG,
SUM((ctdh.GIABAN*ctdh.SOLUONG + ctdh.GIABAN*ctdh.SOLUONG*(ctdh.MUCGIAMGIA/100))) AS TONGTIEN
FROM CHITIETDATHANG ctdh
INNER JOIN MATHANG mh ON mh.MAHANG = ctdh.MAHANG 
GROUP BY ctdh.SOHOADON, mh.TENHANG;

--12

SELECT
lh.MALOAIHANG,
lh.TENLOAIHANG
FROM LOAIHANG lh;

SELECT
lh.MALOAIHANG,
lh.TENLOAIHANG,
mh.TENHANG
FROM LOAIHANG lh
INNER JOIN MATHANG mh ON mh.MALOAIHANG = lh.MALOAIHANG;

SELECT
mh.TENHANG
FROM MATHANG mh
WHERE mh.MALOAIHANG = 'LH01';

SELECT
mh.MALOAIHANG,
SUM(mh.SOLUONG) AS TONGSOLUONG
FROM MATHANG mh
GROUP BY mh.MALOAIHANG;

SELECT
mh.TENHANG,
SUM(mh.SOLUONG)AS TONGSOLUONG
FROM MATHANG mh
GROUP BY mh.TENHANG;

SELECT
SUM(mh.SOLUONG)AS TONGSOLUONG
FROM MATHANG mh;

--13
SELECT
ctdh.MAHANG,
TO_CHAR(ddh.NGAYDATHANG, 'MM') AS THANG,
SUM(ctdh.SOLUONG) AS TONGSOLUONG
FROM CHITIETDATHANG ctdh
INNER JOIN DONDATHANG ddh ON ddh.SOHOADON = ctdh.SOHOADON
AND TO_CHAR(ddh.NGAYDATHANG, 'YYYY') = '2017'
GROUP BY ctdh.MAHANG, TO_CHAR(ddh.NGAYDATHANG, 'MM');

SELECT
ctdh.MAHANG,
SUM(ctdh.SOLUONG) AS TONGSOLUONG
FROM CHITIETDATHANG ctdh
INNER JOIN DONDATHANG ddh ON ddh.SOHOADON = ctdh.SOHOADON
AND TO_CHAR(ddh.NGAYDATHANG, 'MM') = '02'
AND TO_CHAR(ddh.NGAYDATHANG, 'YYYY') = '2017'
GROUP BY ctdh.MAHANG;

--14
UPDATE
DONDATHANG ddh
SET ddh.NGAYCHUYENHANG = ddh.NGAYDATHANG
WHERE ddh.NGAYCHUYENHANG IS NULL;

--15
UPDATE
(SELECT ddh.MAKHACHHANG, ddh.NOIGIAOHANG, kh.DIACHI FROM DONDATHANG ddh INNER JOIN KHACHHANG kh ON kh.MAKHACHHANG = ddh.MAKHACHHANG) aa
SET aa.NOIGIAOHANG = aa.DIACHI
WHERE aa.NOIGIAOHANG IS NULL;

--16 Chưa hoàn thiện
SELECT
ncc.TENCONGTY,
ncc.TENGIAODICH,
ncc.DIACHI,
kh.DIACHI AS DCKHACHHANG,
ncc.DIENTHOAI,
kh.DIENTHOAI AS DTKHACHHANG,
ncc.FAX,
kh.FAX AS FAKHACHHANG,
ncc.EMAIL,
kh.EMAIL AS EMKHACHHANG
FROM NHACUNGCAP ncc
INNER JOIN KHACHHANG kh ON kh.TENCONGTY = ncc.TENCONGTY
AND kh.TENGIAODICH = ncc.TENCONGTY;

UPDATE
(SELECT
kh.DIACHI,
ncc.DIACHI AS DCNCC
FROM NHACUNGCAP ncc
INNER JOIN KHACHHANG kh ON kh.TENCONGTY = ncc.TENCONGTY
AND kh.TENGIAODICH = ncc.TENCONGTY) aaa
SET aaa.DIACHI = aaa.DCNCC;

--17
SELECT
nv.MANHANVIEN,
nv.HO,
nv.TEN,
(nv.LUONGCOBAN + nv.LUONGCOBAN*50/100) AS LUONGCOBAN
FROM NHANVIEN nv
INNER JOIN DONDATHANG ddh ON ddh.MANHANVIEN = nv.MANHANVIEN
INNER JOIN CHITIETDATHANG ctdh ON ctdh.SOHOADON = ddh.SOHOADON
AND ctdh.SOLUONG>100;

update NHANVIEN set LUONGCOBAN=LUONGCOBAN*1.5
where MANHANVIEN in(select nhanvien.manhanvien
from NHANVIEN inner join DONDATHANG on NHANVIEN.MANHANVIEN = DONDATHANG.MANHANVIEN inner join CHITIETDATHANG on DONDATHANG.SOHOADON = CHITIETDATHANG.SOHOADON
group by NHANVIEN.MANHANVIEN
having sum(CHITIETDATHANG.SOLUONG)>100);

--18 Chưa hoàn thiện
SELECT
nv.MANHANVIEN,
nv.HO,
nv.TEN,
ctdh.MAHANG,
SUM(ctdh.SOLUONG) AS TONGSOLUONG,
(nv.LUONGCOBAN*50/100) AS PHUCAP
FROM NHANVIEN nv
INNER JOIN DONDATHANG ddh ON ddh.MANHANVIEN = nv.MANHANVIEN
INNER JOIN CHITIETDATHANG ctdh ON ctdh.SOHOADON = ddh.SOHOADON 
GROUP BY nv.MANHANVIEN, nv.HO, nv.TEN, ctdh.MAHANG, (nv.LUONGCOBAN*50/100)
ORDER BY nv.MANHANVIEN;

--19
SELECT 
nv.MANHANVIEN,
nv.HO,
nv.TEN,
(nv.LUONGCOBAN*75/100) AS LUONGCOBAN
FROM NHANVIEN nv
WHERE nv.MANHANVIEN NOT IN (SELECT DISTINCT
ddh.MANHANVIEN 
FROM DONDATHANG ddh
WHERE TO_CHAR(ddh.NGAYDATHANG, 'YYYY') = '2017');

update NHANVIEN 
set LUONGCOBAN=(1-0.19)*LUONGCOBAN
where NHANVIEN.MANHANVIEN in(select* from(
select NHANVIEN.MANHANVIEN from NHANVIEN full outer join DONDATHANG on NHANVIEN.MANHANVIEN = DONDATHANG.MANHANVIEN
where NHANVIEN.MANHANVIEN not in (select distinct manhanvien from DONDATHANG where extract (year from DONDATHANG.NGAYDATHANG)=2017)
order by NHANVIEN.MANHANVIEN));

--20
SELECT
ddh.SOHOADON,
(SUM((ctdh.GIABAN*ctdh.SOLUONG + ctdh.GIABAN*ctdh.SOLUONG*(ctdh.MUCGIAMGIA/100)))) AS SOTIEN
FROM DONDATHANG ddh
INNER JOIN CHITIETDATHANG ctdh ON ctdh.SOHOADON = ddh.SOHOADON 
GROUP BY ddh.SOHOADON;

DELETE FROM MATHANG mh
WHERE mh.MAHANG IN (SELECT
mh.MAHANG
FROM MATHANG mh
WHERE mh.MAHANG NOT IN (SELECT ctdh.MAHANG FROM CHITIETDATHANG ctdh)
AND mh.SOLUONG = '0');

--3-1
create or replace Procedure INSERTMATHANG
(mh_mahang IN MATHANG.MAHANG%TYPE,
    mh_tenhang IN MATHANG.TENHANG%TYPE,
    mh_macongty IN MATHANG.MACONGTY%TYPE,
    mh_maloaihang IN MATHANG.MALOAIHANG%TYPE,
    mh_soluong IN MATHANG.SOLUONG%TYPE,
    mh_donvitinh IN MATHANG.DONVITINH%TYPE,
    mh_giahang IN MATHANG.GIAHANG%TYPE)
IS
BEGIN
   INSERT
    INTO MATHANG mh(mh.MAHANG, mh.TENHANG, mh.MACONGTY, mh.MALOAIHANG, mh.SOLUONG, mh.DONVITINH, mh.GIAHANG) 
    VALUES (mh_mahang, mh_tenhang, mh_macongty, mh_maloaihang, mh_soluong, mh_donvitinh, mh_giahang);
   commit;
EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;

CALL INSERTMATHANG('MH22', 'Lenovo 22', 'CT09', 'LH01', '150', 'cái', '900000');

--3-2
create or replace PROCEDURE TONGSLMH
       (p_mahang IN CHITIETDATHANG.MAHANG%TYPE,
       ct_tongsohang OUT CHITIETDATHANG.SOLUONG%TYPE)
      IS
      BEGIN
        SELECT SUM(SOLUONG)
        INTO ct_tongsohang
        FROM CHITIETDATHANG ctdh
        WHERE ctdh.MAHANG = p_mahang;
   commit;
EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;

CALL TONGSLMH('MH01');

--3-3
CREATE OR REPLACE TRIGGER TRIGGER1 
BEFORE INSERT ON CHITIETDATHANG
FOR EACH ROW
DECLARE
BEGIN
    --Kiểm tra số lượng hàng trước khi insert ở bảng CHITIETDATHANG
    IF (:NEW.SOLUONG < 1) THEN
      RAISE_APPLICATION_ERROR(-20000,'Không thực hiện được. SOLUONG phải >= 1.');
    END IF;
    --Thay đổi số lượng hàng ở bảng MATHANG insert số lượng hàng ở bảng CHITIETDATHANG
    IF (:NEW.SOLUONG >= 1) THEN
      UPDATE ITSOL.MATHANG mh
      SET mh.SOLUONG = (mh.SOLUONG-:NEW.SOLUONG)
      WHERE mh.MAHANG=:NEW.MAHANG;
    END IF;
END;

CREATE OR REPLACE TRIGGER TRIGGER2
BEFORE UPDATE OF SOLUONG ON CHITIETDATHANG
FOR EACH ROW
DECLARE
BEGIN
    --Kiểm tra số lượng hàng trước khi update ở bảng CHITIETDATHANG
    IF (:NEW.SOLUONG < 1) THEN
      RAISE_APPLICATION_ERROR(-20000,'Không thực hiện được. SOLUONG phải >= 1.');
    END IF;
    --Thay đổi số lượng hàng ở bảng MATHANG update số lượng hàng ở bảng CHITIETDATHANG
    IF (:NEW.SOLUONG >= 1) THEN
      UPDATE ITSOL.MATHANG mh
      SET mh.SOLUONG = (mh.SOLUONG+:OLD.SOLUONG-:NEW.SOLUONG)
      WHERE mh.MAHANG=:NEW.MAHANG;
    END IF;
END;

--3-4
CREATE OR REPLACE TRIGGER TRIGGER3
BEFORE INSERT ON CHITIETDATHANG
FOR EACH ROW
DECLARE
GIAHANG NUMBER;
BEGIN
    SELECT GIAHANG INTO GIAHANG FROM MATHANG WHERE MAHANG = :NEW.MAHANG;
    IF (:NEW.GIABAN > GIAHANG) THEN
      RAISE_APPLICATION_ERROR(-20000,'Không thực hiện được. GIABAN < GIAHANG');
    END IF;
END;
